// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hmtmcwzfpazjbutxhexx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdG1jd3pmcGF6amJ1dHhoZXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDkyNTcsImV4cCI6MjA3Mzk4NTI1N30.SOPEnaj7fCifAUulkyxVvCVZZKi8j2yqtkwzy0UISfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);